version: "3.9"

services:
  network_scanner:
    build: ./network_scanner/
    container_name: rustscan
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    command: bash -c "/app/scripts/startup.sh"
    env_file:
      - .env
    restart: on-failure